//
// Generated file, do not edit! Created by opp_msgtool 6.3 from EnergyResponse.msg.
//

#ifndef __VEINS_ENERGYRESPONSE_M_H
#define __VEINS_ENERGYRESPONSE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace veins {

class EnergyResponse;

}  // namespace veins

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4


namespace veins {

/**
 * Class generated from <tt>EnergyResponse.msg:5</tt> by opp_msgtool.
 * <pre>
 * packet EnergyResponse extends BaseFrame1609_4
 * {
 *     int requestId;
 *     int originAddress;
 *     int responderAddress;
 * 
 *     int nextHopAddress;
 * 
 *     int hopCount = 0;
 * 
 *     double energyAvailable;
 *     double batteryLevel;
 * }
 * </pre>
 */
class EnergyResponse : public ::veins::BaseFrame1609_4
{
  protected:
    int requestId = 0;
    int originAddress = 0;
    int responderAddress = 0;
    int nextHopAddress = 0;
    int hopCount = 0;
    double energyAvailable = 0;
    double batteryLevel = 0;

  private:
    void copy(const EnergyResponse& other);

  protected:
    bool operator==(const EnergyResponse&) = delete;

  public:
    EnergyResponse(const char *name=nullptr, short kind=0);
    EnergyResponse(const EnergyResponse& other);
    virtual ~EnergyResponse();
    EnergyResponse& operator=(const EnergyResponse& other);
    virtual EnergyResponse *dup() const override {return new EnergyResponse(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getRequestId() const;
    virtual void setRequestId(int requestId);

    virtual int getOriginAddress() const;
    virtual void setOriginAddress(int originAddress);

    virtual int getResponderAddress() const;
    virtual void setResponderAddress(int responderAddress);

    virtual int getNextHopAddress() const;
    virtual void setNextHopAddress(int nextHopAddress);

    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);

    virtual double getEnergyAvailable() const;
    virtual void setEnergyAvailable(double energyAvailable);

    virtual double getBatteryLevel() const;
    virtual void setBatteryLevel(double batteryLevel);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const EnergyResponse& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, EnergyResponse& obj) {obj.parsimUnpack(b);}


}  // namespace veins


namespace omnetpp {

template<> inline veins::EnergyResponse *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::EnergyResponse*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __VEINS_ENERGYRESPONSE_M_H

