//
// Generated file, do not edit! Created by opp_msgtool 6.3 from EnergyRequest.msg.
//

#ifndef __VEINS_ENERGYREQUEST_M_H
#define __VEINS_ENERGYREQUEST_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace veins {

class EnergyRequest;

}  // namespace veins

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4


namespace veins {

/**
 * Class generated from <tt>EnergyRequest.msg:5</tt> by opp_msgtool.
 * <pre>
 * packet EnergyRequest extends BaseFrame1609_4
 * {
 *     int requestId;
 *     int originAddress;
 * 
 *     int previousHopAddress;
 * 
 *     int hopCount = 0;
 * 
 *     double energyRequired;
 *     double minimumBattery;
 * }
 * </pre>
 */
class EnergyRequest : public ::veins::BaseFrame1609_4
{
  protected:
    int requestId = 0;
    int originAddress = 0;
    int previousHopAddress = 0;
    int hopCount = 0;
    double energyRequired = 0;
    double minimumBattery = 0;

  private:
    void copy(const EnergyRequest& other);

  protected:
    bool operator==(const EnergyRequest&) = delete;

  public:
    EnergyRequest(const char *name=nullptr, short kind=0);
    EnergyRequest(const EnergyRequest& other);
    virtual ~EnergyRequest();
    EnergyRequest& operator=(const EnergyRequest& other);
    virtual EnergyRequest *dup() const override {return new EnergyRequest(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getRequestId() const;
    virtual void setRequestId(int requestId);

    virtual int getOriginAddress() const;
    virtual void setOriginAddress(int originAddress);

    virtual int getPreviousHopAddress() const;
    virtual void setPreviousHopAddress(int previousHopAddress);

    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);

    virtual double getEnergyRequired() const;
    virtual void setEnergyRequired(double energyRequired);

    virtual double getMinimumBattery() const;
    virtual void setMinimumBattery(double minimumBattery);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const EnergyRequest& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, EnergyRequest& obj) {obj.parsimUnpack(b);}


}  // namespace veins


namespace omnetpp {

template<> inline veins::EnergyRequest *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::EnergyRequest*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __VEINS_ENERGYREQUEST_M_H

