//
// Generated file, do not edit! Created by opp_msgtool 6.3 from EnergyRequest.msg.
//

#ifndef __VEINS_ENERGYREQUEST_M_H
#define __VEINS_ENERGYREQUEST_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace veins {

class EnergyRequest;

}  // namespace veins

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4


namespace veins {

/**
 * Class generated from <tt>EnergyRequest.msg:3</tt> by opp_msgtool.
 * <pre>
 * packet EnergyRequest extends BaseFrame1609_4
 * {
 *     // Shared protocol envelope. originAddress identifies this frame's creator.
 *     int messageType = 1;
 *     long messageId;
 *     int destination = -1;
 *     int requesterId = -1;
 *     int truckId = -1;
 *     int hopLimit = 8;
 *     simtime_t createdAt;
 *     simtime_t expiresAt;
 *     simtime_t requestStarted;
 *     simtime_t requestDeadline;
 *     simtime_t chargingStartedAt;
 *     simtime_t chargingEndsAt;
 *     double energyAmount = 0;
 *     double velocityX = 0;
 *     double velocityY = 0;
 *     int requestHops = 0;
 *     int requestId;
 *     int originAddress;
 *     int previousHopAddress;
 *     int hopCount = 0;
 *     double energyRequired;
 *     double positionX;
 *     double positionY;
 *     double speed;
 *     double heading;
 * }
 * </pre>
 */
class EnergyRequest : public ::veins::BaseFrame1609_4
{
  protected:
    int messageType = 1;
    long messageId = 0;
    int destination = -1;
    int requesterId = -1;
    int truckId = -1;
    int hopLimit = 8;
    ::omnetpp::simtime_t createdAt = SIMTIME_ZERO;
    ::omnetpp::simtime_t expiresAt = SIMTIME_ZERO;
    ::omnetpp::simtime_t requestStarted = SIMTIME_ZERO;
    ::omnetpp::simtime_t requestDeadline = SIMTIME_ZERO;
    ::omnetpp::simtime_t chargingStartedAt = SIMTIME_ZERO;
    ::omnetpp::simtime_t chargingEndsAt = SIMTIME_ZERO;
    double energyAmount = 0;
    double velocityX = 0;
    double velocityY = 0;
    int requestHops = 0;
    int requestId = 0;
    int originAddress = 0;
    int previousHopAddress = 0;
    int hopCount = 0;
    double energyRequired = 0;
    double positionX = 0;
    double positionY = 0;
    double speed = 0;
    double heading = 0;

  private:
    void copy(const EnergyRequest& other);

  protected:
    bool operator==(const EnergyRequest&) = delete;

  public:
    EnergyRequest(const char *name=nullptr, short kind=0);
    EnergyRequest(const EnergyRequest& other);
    virtual ~EnergyRequest();
    EnergyRequest& operator=(const EnergyRequest& other);
    virtual EnergyRequest *dup() const override {return new EnergyRequest(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getMessageType() const;
    virtual void setMessageType(int messageType);

    virtual long getMessageId() const;
    virtual void setMessageId(long messageId);

    virtual int getDestination() const;
    virtual void setDestination(int destination);

    virtual int getRequesterId() const;
    virtual void setRequesterId(int requesterId);

    virtual int getTruckId() const;
    virtual void setTruckId(int truckId);

    virtual int getHopLimit() const;
    virtual void setHopLimit(int hopLimit);

    virtual ::omnetpp::simtime_t getCreatedAt() const;
    virtual void setCreatedAt(::omnetpp::simtime_t createdAt);

    virtual ::omnetpp::simtime_t getExpiresAt() const;
    virtual void setExpiresAt(::omnetpp::simtime_t expiresAt);

    virtual ::omnetpp::simtime_t getRequestStarted() const;
    virtual void setRequestStarted(::omnetpp::simtime_t requestStarted);

    virtual ::omnetpp::simtime_t getRequestDeadline() const;
    virtual void setRequestDeadline(::omnetpp::simtime_t requestDeadline);

    virtual ::omnetpp::simtime_t getChargingStartedAt() const;
    virtual void setChargingStartedAt(::omnetpp::simtime_t chargingStartedAt);

    virtual ::omnetpp::simtime_t getChargingEndsAt() const;
    virtual void setChargingEndsAt(::omnetpp::simtime_t chargingEndsAt);

    virtual double getEnergyAmount() const;
    virtual void setEnergyAmount(double energyAmount);

    virtual double getVelocityX() const;
    virtual void setVelocityX(double velocityX);

    virtual double getVelocityY() const;
    virtual void setVelocityY(double velocityY);

    virtual int getRequestHops() const;
    virtual void setRequestHops(int requestHops);

    virtual int getRequestId() const;
    virtual void setRequestId(int requestId);

    virtual int getOriginAddress() const;
    virtual void setOriginAddress(int originAddress);

    virtual int getPreviousHopAddress() const;
    virtual void setPreviousHopAddress(int previousHopAddress);

    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);

    virtual double getEnergyRequired() const;
    virtual void setEnergyRequired(double energyRequired);

    virtual double getPositionX() const;
    virtual void setPositionX(double positionX);

    virtual double getPositionY() const;
    virtual void setPositionY(double positionY);

    virtual double getSpeed() const;
    virtual void setSpeed(double speed);

    virtual double getHeading() const;
    virtual void setHeading(double heading);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const EnergyRequest& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, EnergyRequest& obj) {obj.parsimUnpack(b);}


}  // namespace veins


namespace omnetpp {

template<> inline veins::EnergyRequest *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::EnergyRequest*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __VEINS_ENERGYREQUEST_M_H

